Added 3 unit tests to ExceptionHandlerAdviceTest.java. Unsure if the …
Automatiserad-testning-och-testverktyg/produkt-api pull request #20
Opened 2024-06-08 11:26 UTC by CardonaCervantes

Unsure if the tests make any sense.
I tried to follow the instruction to only create unit tests and disregard the API tests.

2024-06-09 05:30 UTC, jamieblomerus requested changes
Jag har identifierat ett antal fel i din kod, varav enbart **ett** utav dem **måste** åtgärdas innan vi kan merge:a.

Vänligen läs igenom dessa och åtgärda gärna några av dem. Du måste åtminstone (_för att jag ska godkänna din PR_) åtgärda problemet med att du glömt skriva ditt namn i koden.

I övrigt, bortsett från mina anmärkningar, så har du gjort ett väldigt bra jobb. 👍🏻

2024-06-09 05:30 UTC, jamieblomerus commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +    @DisplayName("unitTestofHandleEntityNotFoundException")
Läsbarheten av detta `DisplayName` skulle kunna förbättras. Syftet med DisplayName är att det ska vara lättare att förstå testets syfte. Således föreslår jag att ändra det till:
```suggestion
    @DisplayName("handleException (EntityNotFoundException)")
```

I denna föreslagna ändring så framkommer det tydligt vilken funktion som testas samt vad den testas mot.

2024-06-09 05:30 UTC, jamieblomerus commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +    @DisplayName("unitTestofHandleBadRequestException")
Läsbarheten av detta `DisplayName` skulle kunna förbättras. Syftet med DisplayName är att det ska vara lättare att förstå testets syfte. Således föreslår jag att ändra det till:
```suggestion
    @DisplayName("handleException (BadRequestException)")
```

I denna föreslagna ändring så framkommer det tydligt vilken funktion som testas samt vad den testas mot.

2024-06-09 05:30 UTC, jamieblomerus commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +    @DisplayName("unitTestofHandleNullPointerException")
I detta fall är ett `DisplayName` troligtvis onödigt, särskilt då det nuvarande är mer svårläst än funktionsnamnet av testet. Således föreslår jag att du tar bort `DisplayName` helt och hållet på detta testfall.

2024-06-09 05:30 UTC, jamieblomerus commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +        BadRequestException badRequestException = new BadRequestException("En produkt med titeln: "+ product.getTitle() + " finns redan");
Här testar du i onödan även klassen `Product`, således är detta ej ett enhetstest. Lösningen på detta är att ta bort användningen av `Product` och inkludera titeln direkt i felmeddelandet.

Se nedan förslag på lösning.

```suggestion
        BadRequestException badRequestException = new BadRequestException("En produkt med titeln: Example Product finns redan");
```

2024-06-09 05:30 UTC, jamieblomerus commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +public class ExceptionHandlerAdviceTest {
#### Måste åtgärdas
Du glömde skriva ut att du hade skrivit denna kod, något Simon sade åt oss att göra. Nedan kommer ett förslag på hur du kan göra detta.

```suggestion
public class ExceptionHandlerAdviceTest { //Skrivet av Juan Sebastian Cardona Cervantes
```

2024-06-09 05:30 UTC, jamieblomerus commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +    }
I detta test så förutsätter man att `EntityNotFoundException` kommer formulera meddelandet "_Produkt med id 0 hittades inte_" vid initiering med id:t `0`, därför liknar detta ett integrationstest.

Jag tror egentligen inte att det är ett särskilt stort problem just i detta fall, men det är bra att tänka på. Om du vill så kan jag – efter att denna PR är merge:ad – modifiera detta testfall åt dig, så att det löser ovan nämnd problematik med hjälp av Mockito.

2024-06-10 18:03 UTC, CardonaCervantes commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +    @DisplayName("unitTestofHandleEntityNotFoundException")
Först vill jag börja med att tacka dig Jamie för att du tar dig tid att gå igenom så pass noggrant som du har gjort. Jag har mycket lite erfarenhet av att skriva kod och all feedback är guld värd.

Har dålig koll på best practice för hur man namnger tester. Ditt förslag låter vettigt.

2024-06-10 18:03 UTC, CardonaCervantes commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +    @DisplayName("unitTestofHandleBadRequestException")
Samma som ovan.

2024-06-10 18:06 UTC, CardonaCervantes commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +    @DisplayName("unitTestofHandleNullPointerException")
Tänkte jag skulle ha med alla för att vara konsekvent, men som du säger:
"handleNullPointerException (NullPointerException)" är långt och obegripligt.

2024-06-10 18:26 UTC, CardonaCervantes commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +        BadRequestException badRequestException = new BadRequestException("En produkt med titeln: "+ product.getTitle() + " finns redan");
Här snurrade jag till det ordentligt. Ditt förslag gör testet mycket mer avskalat vilket är bra. Men jag förstår inte vad det är som testas. Jag uppfattar ditt förslag som cirkulärt och det var här jag gick vilse första gången. Jag fick för mig att man ville testa att textsträngen som hämtas från exceptionsklasserna stämmer med förväntat utfall. Jag frågar dig mer vid nästa sprintmöte.

2024-06-10 18:26 UTC, CardonaCervantes commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +public class ExceptionHandlerAdviceTest {
Tack för påminnelsen!

2024-06-10 18:29 UTC, CardonaCervantes commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +    }
Du pekar på kruxet som jag inte lyckades lösa, vilket är var gränsen mellan enhetstest och integrationstest går. Men det är kanske samma missförstånd från min sida som jag gjorde i badRequestException. Återkommer med frågor vid nästa sprintmöte.

Tack igen för alla dina kommentarer Jamie!

2024-06-20 11:08 UTC, CardonaCervantes commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +    }
Återkom gärna med ett förslag!

2024-06-20 21:46 UTC, jamieblomerus commented on src/test/java/com/example/produktapi/service/ExceptionHandlerAdviceTest.java
> +    }
Jag tror vi tyvärr får skippa att åtgärda detta med hänsyn till hur lite tid vi har kvar, så stort problem är det trots allt inte. Jag kommer granska resterande av dina kodändringar och sedan lämna en ny review.

2024-06-20 21:49 UTC, jamieblomerus approved these changes
**LGTM!**

De brister jag tidigare anmärkt på är åtgärdade och koden har en huvudsakligen bra kvalité. Bra jobbat!

2024-06-22 11:56 UTC, jamieblomerus commented
@CardonaCervantes Vänligen kom ihåg att merge:a denna PR.

2024-06-25 14:32 UTC, merged